// Generated by CoffeeScript 1.6.2
(function() {
  var db;

  db = require('../../lib/models/db');

  describe('db', function() {
    it('should be defined', function() {
        console.log('merda')
      expect(db).toBeDefined();
    });
  });

}).call(this);
